# Generated by Django 4.0.1 on 2022-02-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_profiles_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
