# Generated by Django 4.0.1 on 2022-02-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_profiles_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
